name: PyInstaller Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-20.04, windows-latest, macos-latest]
        os: [macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # e.g., 3.x, 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel mtranslate charset-normalizer requests regex tqdm appdata pyinstaller kivy==2.2.0
        pip install -e . --no-build-isolation

    - name: Build with PyInstaller (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "replace kivy/logger.py"
        $KIVYROOT = python -c "import kivy; print(kivy.__path__[0])"
        Copy-Item "gui\modified_logger.py" "$KIVYROOT\logger.py"
        cd gui
        echo "generate spec file"
        pyi-makespec --noupx --debug=all --onefile --noconsole --add-data ".\guipage\page.kv;.\guipage" --add-data ".\guipage\dialog.kv;.\guipage" --add-data ".\guipage\preferencespage.kv;.\guipage" --add-data ".\yahei.ttf;." --hidden-import win32timezone MathTranslate.py
        echo "build executable"
        #pyinstaller MathTranslate.spec 2>&1 | findstr /V /C:"DEBUG" | findstr /V /C:"TRACE"
        pyinstaller --noconfirm MathTranslate.spec

        pyi-makespec --noupx --debug=all --onefile update.py
        pyinstaller --noconfirm update.spec

    - name: Build with PyInstaller (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "replace kivy/logger.py"
        KIVYROOT=$(python -c "import kivy; print(kivy.__path__[0])")
        cp gui/modified_logger.py ${KIVYROOT}/logger.py
        sudo apt-get install -y xvfb
        cd gui
        echo "generate spec file"
        pyi-makespec --onefile --noconsole --add-data ./guipage/page.kv:./guipage --add-data ./guipage/dialog.kv:./guipage --add-data ./guipage/preferencespage.kv:./guipage --add-data ./yahei.ttf:./ MathTranslate.py
        echo "build executable"
        xvfb-run pyinstaller MathTranslate.spec 2>&1 | awk '!/DEBUG/ && !/TRACE/'

        pyi-makespec --onefile update.py
        xvfb-run pyinstaller update.spec | awk '!/DEBUG/ && !/TRACE/'

    - name: Build with PyInstaller (macOS)
      if: runner.os == 'macOS'
      run: |
        echo "replace kivy/logger.py"
        KIVYROOT=$(python -c "import kivy; print(kivy.__path__[0])")
        cp gui/modified_logger.py ${KIVYROOT}/logger.py
        cd gui
        echo "generate spec file"
        pyi-makespec --onefile --noconsole --add-data ./guipage/page.kv:./guipage --add-data ./guipage/dialog.kv:./guipage --add-data ./guipage/preferencespage.kv:./guipage --add-data ./yahei.ttf:./ MathTranslate.py
        echo "build executable"
        pyinstaller MathTranslate.spec 2>&1 | awk '!/DEBUG/ && !/TRACE/'
        rm -r dist/MathTranslate.app

        pyi-makespec --onefile update.py
        pyinstaller update.spec | awk '!/DEBUG/ && !/TRACE/'

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MathTranslate-${{ matrix.os }}
        path: ./gui/dist/

